name: restore

runs:
  using: composite
  steps:
    - name: Install dotnet
      uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 # v5
      with:
        global-json-file: global.json
        cache: true
        cache-dependency-path: "**/packages.lock.json"

    - name: Restore
      shell: bash
      run: dotnet restore --locked-mode
