name: restore

runs:
  using: composite
  steps:
    - name: Install dotnet
      uses: actions/setup-dotnet@2016bd2012dba4e32de620c46fe006a3ac9f0602 # v5
      with:
        global-json-file: global.json
        cache: true
        cache-dependency-path: "**/packages.lock.json"

    - name: Restore
      shell: bash
      run: dotnet restore --locked-mode
