name: restore

runs:
  using: composite
  steps:
    - name: Install dotnet
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4
      with:
        global-json-file: global.json
        cache: true
        cache-dependency-path: "**/packages.lock.json"

    - name: Restore
      shell: bash
      run: dotnet restore --locked-mode
